In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
#creating numpy array
#casting the list into array
my_list = [1,2,3]

In [5]:
x = np.array(my_list)

In [6]:
type(x)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
mat1 = np.array(my_matrix)

In [10]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#range function in python
list(range(0,5))

[0, 1, 2, 3, 4]

In [16]:
#RANGE FUNCTION IN NUMPY- Arange - Array range
ran1 = np.arange(0,5)

In [17]:
type(ran1)

numpy.ndarray

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
type(1.44)

float

In [23]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
##returns evenly spaced between two numbers start stop , how many numbers in between 
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [32]:
#identity matrix, square matrix having same number of rows and columns
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
#random library , gives matrix of random numbers in 5,4 matrix
np.random.rand(5,4)

array([[0.01629102, 0.47563177, 0.25599278, 0.02804646],
       [0.71837394, 0.03849935, 0.63598414, 0.01793876],
       [0.17035398, 0.76769081, 0.5680099 , 0.29067966],
       [0.38899328, 0.40605135, 0.35151635, 0.64730607],
       [0.83838199, 0.28661692, 0.26538769, 0.85698562]])

In [37]:
#sampling from standard normal random distribution also called as gaussian distribution
np.random.randn(5,4)

array([[ 0.52333432,  0.09005077, -1.02194462, -0.77866985],
       [ 1.35154275,  0.43451684, -0.34082834, -0.56508903],
       [-0.084977  ,  1.55457367, -1.07375739, -0.8788687 ],
       [ 0.95217175,  1.71790745, -0.3960361 ,  1.08465691],
       [-1.32540471,  0.07472738,  0.3028524 ,  1.19824927]])

In [42]:
#random integer
np.random.randint(1,100,10)

array([33, 10, 74, 75, 54, 36, 59, 27, 51, 88])

In [47]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [50]:
arr.reshape(5,5) #reshape in the form of matrix from array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.dtype #data type

dtype('int64')

In [54]:
ranarr.max() # Maxinmum or heighest number in the array

42

In [55]:
ranarr.argmax() # Return index location of the heighest number in the array

9

In [56]:
ranarr

array([18, 41, 19,  3, 27, 13,  9,  3, 16, 42])

In [57]:
ranarr.argmin()

3