In [1]:
import numpy as np

In [2]:
#### Numpy operations

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
## performs operations by element by element

In [8]:
1/arr

/var/folders/z4/qlbxj0v50xnbgt9bbgdzbml00000gn/T/ipykernel_27037/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
0/0

ZeroDivisionError: division by zero

In [11]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [13]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [15]:
np.sqrt(arr) #Square root of the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
arr.max()

9

In [17]:
np.max(arr)

9

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [19]:
np.log(arr)

/var/folders/z4/qlbxj0v50xnbgt9bbgdzbml00000gn/T/ipykernel_27037/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [20]:
 arr[:5]

array([0, 1, 2, 3, 4])

In [21]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
#broadcast
arr[0:5] = 100

In [23]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [24]:
arr = np.arange(0,10)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
slice_of_arr = arr[0:6]

In [27]:
slice_of_arr[:] = 99

In [28]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [30]:
arr_copy = arr.copy()

In [31]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [32]:
arr_copy[:] 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [33]:
#indexing Matrix or 2 dimensional array

In [34]:
#mat[row, col]
#mat[row][col]

In [37]:
mat = np.array([[5,10,15],[23,23,23], [5,5,5]])

In [38]:
#indexing entier row -
mat[2]

array([5, 5, 5])

In [39]:
mat [2][2]

5

In [40]:
mat[1][2]

23

In [41]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr2[(arr2) > 3]

array([4, 5, 6, 7, 8, 9])